# Name
site_name: Ellipsis-TPM

# Docs directory
docs_dir: ./

# Docs page index
pages:
  - Home: index.md
  - Install: install.md
  - Switching from TPM: tpm.md
  - Usage: usage.md
  - Writing plugins: plugins.md
  - About: about.md

# Theme
theme: readthedocs
